config/routes.rb
Rails.application.routes.draw do
  # lelangind
  root 'lelangind#index', as: 'lelangind_index'
  get 'lelang', to: 'lelangind#lelang', as: 'lelangind_lelang_barang'
  get 'lelang/:id/', to: 'lelangind#ikut_lelang', as: 'lelangind_ikut_lelang'
  post 'lelang/:id/', to: 'lelangind#penawaran', as: 'lelangind_ajukan_penawaran'
  get '/history/', to: 'lelangind#history', as: 'lelangind_history'
  get '/:id/profile', to: 'lelangind#profile', as: 'lelangind_profile'
  patch '/:id/profile/', to: 'lelangind#update_profile', as: 'lelangind_update_profile'

  # auth
  get '/auth/', to: 'auth#new',  as: 'auth_new'
  post '/create_m_auth', to: 'auth#create_m_auth', as: 'create_m_auth'
  post '/auth/', to: 'auth#create_m_user', as: 'create_m_user'
  get '/petugas/auth/', to: 'auth#new_p', as: 'auth_p_new'
  post '/create_p_auth', to: 'auth#create_p_auth', as: 'create_p_auth'
  delete '/destroy_session_m/:id', to: 'auth#destroy_session_m', as: 'destroy_s_m'
  delete '/destroy_session_p/:id', to: 'auth#destroy_session_p', as: 'destroy_s_p'

  # petugas
  get '/petugas/profile/:id', to: 'petugas#profile_petugas', as: 'profile_p'
  patch '/petugas/profile/:id', to: 'petugas#update_profile_p', as: 'update_profile_p'

  get '/petugas/', to: 'petugas#index', as: 'petugas_index'

  get '/petugas/pendataan-barang', to: 'petugas#pendataan_barang', as: 'data_barang_p'
  post '/petugas/pendataan-barang', to: 'petugas#create_new_barang', as: 'create_new_barang'
  get '/petugas/pendataan-barang/:id',to: 'petugas#detail_barang_item', as: 'detail_barang_item'
  get '/petugas/pendataan-barang/:id/edit', to: 'petugas#edit_barang', as: 'edit_barang'
  patch '/petugas/pendataan-barang/:id/edit', to: 'petugas#update_barang', as: 'update_barang'
  delete '/petugas/pendataan-barang/:id/delete', to: 'petugas#destroy_barang', as: 'destroy_barang' 

  get '/petugas/lelang/', to: 'petugas#barang_lelang', as: 'barang_lelang_p'
  get '/petugas/lelang/:id', to: 'petugas#barang_lelang_detail', as: 'barang_lelang_detail'
  post '/petugas/lelang/:id/buka-lelang', to: 'petugas#buka_lelang', as: 'buka_lelang'
  post '/petugas/lelang/:id/tutup-lelang', to: 'petugas#tutup_lelang', as: 'tutup_lelang'

  get '/petugas/daftar-petugas/', to: 'petugas#manage_petugas', as: 'manage_petugas'
  post '/petugas/daftar-petugas/', to: 'petugas#create_new_petugas', as: 'create_new_petugas'
  
  get '/petugas/laporan/', to: 'petugas#generate_laporan', as: 'laporan'
end

app/models/petugas.rb
class Petugas < ApplicationRecord

    validates :nama_petugas, presence: true, length: { minimum:4, maximum:20 }
    validates :username, presence: true, uniqueness: true, length: { minimum: 5, maximum: 20 }
    validates :level_id, presence: true, numericality: true

    has_secure_password
end

app/controllers/petugas_controller.rb
class PetugasController < ApplicationController

  before_action :p_signed_in?
  helper_method :current_user_p

  layout 'petugas'

  def index

  end

  def pendataan_barang
    @new_barang = Barang.new
    @list_barang = Barang.paginate(page: params[:page], per_page: 6).order(created_at: :desc)
  end

  def create_new_barang
    @list_barang = Barang.paginate(page: params[:page], per_page: 6).order(created_at: :desc)
    @new_barang = Barang.new(new_barang_params)
    if @new_barang.save
      redirect_to detail_barang_item_path(@new_barang), notice: 'Barang berhasil ditambahkan!'
    else
      render :pendataan_barang
    end
  end

  def detail_barang_item
    @item = Barang.find(params[:id])
  end

  def edit_barang
    @item = Barang.find(params[:id])
  end

  def update_barang
    @item = Barang.find(params[:id])
    if @item.update(barang_edit_params)
      redirect_to detail_barang_item_path(@item), notice: 'Berhasil update barang!'
    else
      render :edit_barang
    end
  end

  def destroy_barang
    @find = Barang.find(params[:id])
    if @find.destroy
      redirect_to data_barang_p_path, notice: 'Berhasil menghapus barang'
    else
      redirect_to detail_barang_item_path(@find), alert: 'Gagal menghapus barang'
    end
  end

  def barang_lelang
    @barang = Barang.all.where(nil)
    @barang = Barang.all.where('nama_barang like ?', "%#{params[:nama_barang]}%") if params[:nama_barang].present?
  end

  def barang_lelang_detail
    @item = Barang.find(params[:id])
  end

  def buka_lelang
    @item = Barang.find(params[:id])
    buka = Lelang.create(barang_id: @item.id, tgl_lelang: DateTime.current.to_date, petugas_id: current_user_p.id, status: 'dibuka')
    if buka
      redirect_to barang_lelang_detail_path(barang_id: @item.id), notice: "Lelang #{@item.nama_barang} telah dibuka!"
    else
      redirect_to barang_lelang_detail_path, alert: 'Gagal buka lelang!'
    end
  end

  def tutup_lelang
    item = Barang.find(params[:id])
    user_win = item.lelang.histories.max.masyarakat.id
    penawaran = item.lelang.histories.max.penawaran_harga
    tutup = Lelang.where(id: item.lelang.id).update(harga_akhir: penawaran, masyarakat_id: user_win, status: 'ditutup')
    if tutup
      redirect_to barang_lelang_detail_path(barang_id: item.id), notice: "Lelang #{item.nama_barang} telah ditutup!"
    else
      redirect_to barang_lelang_detail_path, alert: 'Gagal tutup lelang!'
    end
  end

  def manage_petugas
    if current_user_p.level_id == 2
      redirect_to petugas_index_path, alert: 'Tidak mempunyai akses untuk daftar petugas!'
    end
    @new_petugas = Petugas.new
    @list_petugas = Petugas.paginate(page: params[:page], per_page: 6).order(created_at: :desc).where(level_id: 2)
  end

  def create_new_petugas
    @list_petugas = Petugas.paginate(page: params[:page], per_page: 6).order(created_at: :desc)
    @new_petugas = Petugas.new(new_petugas_params)
    if @new_petugas.save
      redirect_to manage_petugas_path, notice: 'Akun Petugas berhasil dibuat!'
    else
      render :manage_petugas
    end
  end

  def generate_laporan
    b_awal = Date.parse("1/#{params[:month]}/#{params[:year]}") if params[:month].present? && params[:year].present?
    b_akhir = b_awal.end_of_month if params[:month].present? && params[:year].present?
    @cari = Lelang.where(status: 'ditutup').where(nil)
    @cari = Lelang.where(status: 'ditutup').where(created_at: b_awal..b_akhir) if params[:month].present? && params[:year].present?
  end

  def profile_petugas
    @petugas_id = Petugas.find(params[:id])
  end

  def update_profile_p
    @petugas_id = Petugas.find(params[:id])
    if @petugas_id.update(profile_edit_params)
      redirect_to profile_p_path, notice: 'Update profile berhasil!'
    else
      render :profile_petugas
    end
  end

  private
  def profile_edit_params
    params.require(:petugas).permit(:nama_petugas, :username)
  end

  def new_petugas_params
    params.require(:petugas).permit(:nama_petugas, :username, :password, :level_id)
  end

  def new_barang_params
    params.require(:barang).permit(:nama_barang, :img_barang, :tgl, :harga_awal, :deskripsi_barang)
  end

  def barang_edit_params
    params.require(:barang).permit(:nama_barang, :img_barang, :deskripsi_barang)
  end
end

app/helpers/petugas_helper.rb
module PetugasHelper
end

app/views/petugas/barang_lelang.html.erb
<% if notice %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-md-12">
      <div class="d-flex justify-content-end">
          <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><%= link_to 'Home', petugas_index_path %></li>
                <li class="breadcrumb-item active" aria-current="page">Barang Lelang</li>
              </ol>
          </nav>
      </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <%= form_tag barang_lelang_p_path, method: :get do %>
          <div class="form-group">
            <label>Cari barang</label>
            <div class="row">
              <div class="col-md-9">
                <div class="form-group">
                  <%= text_field_tag :nama_barang, params[:nama_barang], class: 'form-control', placeholder: 'cari nama barang ...', autocomplete: 'off' %>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <%= button_tag type: 'submit', class: 'form-control btn-primary' do %>
                    <i class="nc-icon nc-zoom-split"></i>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <% @barang.each do |b| %>
    <div class="col-md-4">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title mb-0 text-capitalize"><%= b.nama_barang %></h4>
          <hr>
        </div>
        <div class="card-body">
          <div class="form-group"> 
            <label class="mb-0">Harga Awal</label>
            <p class="mt-0 text-capitalize">Rp. <%= number_with_delimiter(b.harga_awal) %></p>
          </div>
          <div class="form-group">
            <% lelang = Lelang.find_by(barang_id: b.id) %>
            <% if lelang.blank? %>
              <label class="mb-0">Status Lelang</label>
              <p class="mt-0 text-danger">Belom dibuka</p>
            <% else %>
              <label class="mb-0">Status Lelang</label>
              <% if lelang.status == "dibuka" %>
                <p class="mt-0 text-capitalize text-success">Dibuka</p>
              <% elsif lelang.status == "ditutup" %>
                <p class="mt-0 text-capitalize text-danger">Ditutup</p>
              <% else %>
                
              <% end %>
            <% end %>
          </div>
          <hr>
          <%= link_to 'Lihat', barang_lelang_detail_path(b), class: 'btn btn-primary btn-block' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/petugas/detail_barang_item.html.erb
<% if notice %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
<% end %>
<% if alert %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
    <div class="col-md-12">
        <div class="d-flex justify-content-end">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><%= link_to 'Home', petugas_index_path %></li>
                  <li class="breadcrumb-item"><%= link_to 'Pendataan Barang', data_barang_p_path %></li>
                  <li class="breadcrumb-item active" aria-current="page"><%= @item.nama_barang %></li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"><%= @item.nama_barang %></h4>
                <p class="text-muted">Detail barang <%= @item.nama_barang %></p>
                <hr>
            </div>
            <div class="card-body">
                <img src="<%= @item.img_barang %>" class="img-thumbnail" alt="img_barang_<%= @item.nama_barang %>">
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card">
            <div class="card-body">
                <div class="form-group">
                    <label>Tanggal dibuat</label>
                    <p><%= @item.tgl.strftime("%e %b %Y") %></p>
                </div>
                <div class="form-group">
                    <label>Harga Awal</label>
                    <p>Rp. <%= number_with_delimiter(@item.harga_awal) %></p>
                </div>
                <div class="form-group">
                    <label>Deskripsi barang</label>
                    <p><%= @item.deskripsi_barang %></p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="d-flex justify-content-center">
                    <%= link_to edit_barang_path(@item), class: 'btn btn-info' do %>
                        <i class="nc-icon nc-ruler-pencil"></i>
                        Edit Barang
                    <% end %>
                    <%= link_to '#', class: 'btn btn-danger', data: {toggle: 'modal', target: '#delete-alert'} do %>
                        <i class="nc-icon nc-simple-remove"></i>
                        Hapus
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="delete-alert" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ingin menghapus barang?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Dengan menghapus barang ini, maka Lelang dan History penawaran semuanya akan ikut terhapus. <br>
        Anda yakin?  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= link_to 'Ya! Hapus', destroy_barang_path, class: 'btn btn-primary', method: :delete %>
      </div>
    </div>
  </div>
</div>

app/views/petugas/edit_barang.html.erb
<% if notice %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
<% end %>
<% if @item.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h5><%= pluralize(@item.errors.count, "error") %> Upss!, Gagal tambah barang :</h5>
    <hr>
    <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="row">
    <div class="col-md-12">
        <div class="d-flex justify-content-end">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><%= link_to 'Home', petugas_index_path %></li>
                  <li class="breadcrumb-item"><%= link_to 'Pendataan Barang', data_barang_p_path %></li>
                  <li class="breadcrumb-item"><%= link_to @item.nama_barang, detail_barang_item_path(@item) %></li>
                  <li class="breadcrumb-item active" aria-current="page">Edit</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Edit Barang</h4>
                <hr>
            </div>
            <div class="card-body">
                <%= form_with model: @item, url: update_barang_path, local: true do |b| %>
                    <div class="form-group">
                        <%= b.label 'Nama barang' %>
                        <%= b.text_field :nama_barang, class: 'form-control', placeholder: 'Contoh : lemari', autocomplete: 'off' %>
                    </div>
                    <div class="form-group">
                        <%= b.label 'Foto barang' %>
                        <div class="custom-file">
                            <%= b.file_field :img_barang, class: 'custom-file-input', id: 'customFile' %>
                            <label class="custom-file-label" for="customFile">Pilih Foto Barang</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <%= b.label 'Deskripsi barang' %>
                        <%= b.text_area :deskripsi_barang, class: 'form-control', placeholder: 'Deskripsi barang ...', autocomplete: 'off' %>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="update ml-auto mr-auto">
                                <%= b.submit  class: 'btn btn-primary btn-round' %>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    
</div>

app/views/petugas/generate_laporan.html.erb
<% if notice %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-md-12">
      <div class="d-flex justify-content-end">
          <nav aria-label="breadcrumb">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><%= link_to 'Home', petugas_index_path %></li>
                <li class="breadcrumb-item active" aria-current="page">Laporan</li>
              </ol>
          </nav>
      </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        <%= form_tag laporan_path, method: :get do %>
            <div class="form-group">
              <label>Cari</label>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <%= select_month(0, { prompt: '--Pilih bulan--' }, { class: 'form-control', id: 'month', name: 'month' }) %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <%= select_year(0, { prompt: '--Pilih tahun--' }, { class: 'form-control', id: 'year', name: 'year' }) %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <%= submit_tag 'Cari', class: 'btn btn-primary btn-block' %>
                  </div>
                </div>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <p><%= @cari.count %> orang pemenang</p>
        <table class="table">
          <thead>
            <tr>
              <th>No</th>
              <th>Barang Lelang</th>
              <th>Pemenang</th>
              <th>Penawaran</th>
              <th>Tanggal</th>
            </tr>
          </thead>
          <tbody>
            <% @cari.each.with_index do |c, index| %>
              <tr>
                <td><%= index+1 %></td>
                <td><%= c.barang.nama_barang %></td>
                <td><%= Masyarakat.find(c.masyarakat_id).nama_lengkap %></td>
                <td>Rp. <%= number_with_delimiter(c.harga_akhir) %></td>
                <td><%= c.created_at.strftime('%d-%m-%Y') %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% if @cari.blank? %>
          <p class="text-center">Tidak ada data</p>
        <% else %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/petugas/manage_petugas.html.erb
<% if notice %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
<% end %>
<% if @new_petugas.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h5><%= pluralize(@new_petugas.errors.count, "error") %> Upss!, Gagal tambah petugas :</h5>
    <hr>
    <ul>
      <% @new_petugas.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="row">
    <div class="col-md-12">
        <div class="d-flex justify-content-end">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><%= link_to 'Home', petugas_index_path %></li>
                  <li class="breadcrumb-item active" aria-current="page">Daftar Petugas</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Tambah Petugas</h4>
                <p class="text-muted">Buat akun untuk petugas</p>
                <hr>
            </div>
            <div class="card-body">
                <%= form_with model: @new_petugas, url: create_new_petugas_path, local: true do |p| %>
                    <div class="form-group">
                        <%= p.label 'Nama petugas' %>
                        <%= p.text_field :nama_petugas, class: 'form-control', placeholder: 'jajang supratman', autocomplete: 'off' %>
                    </div>
                    <div class="form-group">
                        <%= p.label 'Username' %>
                        <%= p.text_field :username, class: 'form-control', placeholder: 'jajang221', autocomplete: 'off' %>
                    </div>
                    <div class="form-group">
                        <%= p.label 'Password' %>
                        <%= p.password_field :password, class: 'form-control', placeholder: '••••••' %>
                    </div>
                    <div class="form-group">
                        <%= p.label 'Level' %>
                        <%= p.select(:level_id, options_for_select(Level.all.map{ |l| [l.level, l.id] }), { prompt: '---- pilih level ----' }, { class: 'form-control' }) %>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="update ml-auto mr-auto">
                                <%= p.submit 'Tambah Petugas', class: 'btn btn-primary btn-round' %>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Daftar Petugas</h4>
                <p class="text-muted">Daftar akun pengurus lelang</p>  
                <hr> 
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="example" class="table table-hover table-sm">
                        <thead class="text-primary">
                            <tr>
                                <th>No</th>
                                <th>Nama Petugas</th>
                                <th>Username</th>
                                <th>Level</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @list_petugas.each.with_index(@list_petugas.offset+1) do |list, index| %>
                                <tr>
                                    <td><%= index %></td>
                                    <td><%= list.nama_petugas %></td>
                                    <td><%= list.username %></td>
                                    <td><%= Level.find(list.level_id).level %></td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                    <div class="d-flex justify-content-end">
                        <%= will_paginate @list_petugas, renderer: BootstrapPagination::Rails %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/petugas/pendataan_barang.html.erb
<% if notice %>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
<% end %>
<% if @new_barang.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h5><%= pluralize(@new_barang.errors.count, "error") %> Upss!, Gagal tambah barang :</h5>
    <hr>
    <ul>
      <% @new_barang.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="row">
    <div class="col-md-12">
        <div class="d-flex justify-content-end">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><%= link_to 'Home', petugas_index_path %></li>
                  <li class="breadcrumb-item active" aria-current="page">Pendataan Barang</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Tambah Barang</h4>
                <p class="text-muted">Tambah barang untuk lelang</p>
                <hr>
            </div>
            <div class="card-body">
                <%= form_with model: @new_barang, url: create_new_barang_path, local: true do |b| %>
                    <div class="form-group">
                        <%= b.label 'Nama barang' %>
                        <%= b.text_field :nama_barang, class: 'form-control', placeholder: 'Contoh : lemari', autocomplete: 'off' %>
                    </div>
                    <div class="form-group">
                        <%= b.label 'Foto barang' %>
                        <div class="custom-file">
                            <%= b.file_field :img_barang, class: 'custom-file-input', id: 'customFile' %>
                            <label class="custom-file-label" for="customFile">Pilih Foto Barang</label>
                        </div>
                    </div>
                    <%= b.date_field :tgl, class: 'form-control', hidden: 'true', placeholder: 'dd/mm/yyyy', autocomplete: 'off', value: DateTime.current.to_date, readonly: true %>
                    <div class="form-group">
                        <%= b.label 'Harga awal' %>
                        <%= b.text_field :harga_awal, class: 'form-control', placeholder: 'Contoh : 50000', autocomplete: 'off' %>
                    </div>
                    <div class="form-group">
                        <%= b.label 'Deskripsi barang' %>
                        <%= b.text_area :deskripsi_barang, class: 'form-control', placeholder: 'Deskripsi barang ...', autocomplete: 'off' %>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="update ml-auto mr-auto">
                                <%= b.submit 'Tambah Barang', class: 'btn btn-primary btn-round' %>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Daftar Barang</h4>
                <p class="text-muted">Daftar barang lelang</p>  
                <hr> 
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="data-barang" class="table table-hover table-sm">
                        <thead class="text-primary">
                            <tr>
                                <th>No</th>
                                <th>Nama Barang</th>
                                <th>Harga Awal</th>
                                <th>#</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @list_barang.each.with_index(@list_barang.offset+1) do |b, index| %>
                                <tr>
                                    <td><%= index %></td>
                                    <td><%= b.nama_barang %></td>
                                    <td>Rp. <%= number_with_delimiter(b.harga_awal) %></td>
                                    <td>
                                        <%= link_to detail_barang_item_path(b), class: 'btn btn-sm btn-primary' do %>
                                            <i class="nc-icon nc-spaceship"></i>
                                            Lihat
                                        <% end %>
                                    </td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                    <div class="d-flex justify-content-end">
                        <%= will_paginate @list_barang, renderer: BootstrapPagination::Rails %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>