config/routes.rb
Rails.application.routes.draw do
  # lelangind
  root 'lelangind#index', as: 'lelangind_index'
  get 'lelang', to: 'lelangind#lelang', as: 'lelangind_lelang_barang'
  get 'lelang/:id/', to: 'lelangind#ikut_lelang', as: 'lelangind_ikut_lelang'
  post 'lelang/:id/', to: 'lelangind#penawaran', as: 'lelangind_ajukan_penawaran'
  get '/history/', to: 'lelangind#history', as: 'lelangind_history'
  get '/:id/profile', to: 'lelangind#profile', as: 'lelangind_profile'
  patch '/:id/profile/', to: 'lelangind#update_profile', as: 'lelangind_update_profile'

  # auth
  get '/auth/', to: 'auth#new',  as: 'auth_new'
  post '/create_m_auth', to: 'auth#create_m_auth', as: 'create_m_auth'
  post '/auth/', to: 'auth#create_m_user', as: 'create_m_user'
  get '/petugas/auth/', to: 'auth#new_p', as: 'auth_p_new'
  post '/create_p_auth', to: 'auth#create_p_auth', as: 'create_p_auth'
  delete '/destroy_session_m/:id', to: 'auth#destroy_session_m', as: 'destroy_s_m'
  delete '/destroy_session_p/:id', to: 'auth#destroy_session_p', as: 'destroy_s_p'

  # petugas
  get '/petugas/profile/:id', to: 'petugas#profile_petugas', as: 'profile_p'
  patch '/petugas/profile/:id', to: 'petugas#update_profile_p', as: 'update_profile_p'

  get '/petugas/', to: 'petugas#index', as: 'petugas_index'

  get '/petugas/pendataan-barang', to: 'petugas#pendataan_barang', as: 'data_barang_p'
  post '/petugas/pendataan-barang', to: 'petugas#create_new_barang', as: 'create_new_barang'
  get '/petugas/pendataan-barang/:id',to: 'petugas#detail_barang_item', as: 'detail_barang_item'
  get '/petugas/pendataan-barang/:id/edit', to: 'petugas#edit_barang', as: 'edit_barang'
  patch '/petugas/pendataan-barang/:id/edit', to: 'petugas#update_barang', as: 'update_barang'
  delete '/petugas/pendataan-barang/:id/delete', to: 'petugas#destroy_barang', as: 'destroy_barang' 

  get '/petugas/lelang/', to: 'petugas#barang_lelang', as: 'barang_lelang_p'
  get '/petugas/lelang/:id', to: 'petugas#barang_lelang_detail', as: 'barang_lelang_detail'
  post '/petugas/lelang/:id/buka-lelang', to: 'petugas#buka_lelang', as: 'buka_lelang'
  post '/petugas/lelang/:id/tutup-lelang', to: 'petugas#tutup_lelang', as: 'tutup_lelang'

  get '/petugas/daftar-petugas/', to: 'petugas#manage_petugas', as: 'manage_petugas'
  post '/petugas/daftar-petugas/', to: 'petugas#create_new_petugas', as: 'create_new_petugas'
  
  get '/petugas/laporan/', to: 'petugas#generate_laporan', as: 'laporan'
end

app/controllers/lelangind_controller.rb
class LelangindController < ApplicationController

  before_action :m_signed_in?, only: [:penawaran, :history, :profile, :update_profile]
  helper_method :current_user_m

  layout 'lelangind'

  def index
    
  end

  def lelang
    @lelang = Lelang.all.where(status: 'dibuka').order(created_at: :desc)
  end

  def ikut_lelang
    @item = Lelang.find(params[:id])
  end

  def penawaran
    item = Lelang.find(params[:id])
    penawaran_pertama = item.histories
    if penawaran_pertama.blank?
      pengajuan = params[:penawaran_harga]
      harga_awal = item.barang.harga_awal
      if (pengajuan.to_i <= harga_awal.to_i)
        redirect_to lelangind_ikut_lelang_path(item), alert: 'Penawaran pertama tidak boleh kurang dari harga awal barang!'
      else
        History.create(lelang_id: item.id, barang_id: item.barang.id, masyarakat_id: current_user_m.id, penawaran_harga: pengajuan)
        redirect_to lelangind_ikut_lelang_path(item), notice: 'Berhasil mengajukan barang!'
      end
    else
      harga_max = item.histories.max.penawaran_harga
      pengajuan = params[:penawaran_harga]
      if (pengajuan.to_i <= harga_max.to_i)
        redirect_to lelangind_ikut_lelang_path(item), alert: 'Pengajuan harga harus melebihi harga tertinggi lelang!'
      else
        History.create(lelang_id: item.id, barang_id: item.barang.id, masyarakat_id: current_user_m.id, penawaran_harga: pengajuan)
        redirect_to lelangind_ikut_lelang_path(item), notice: 'Berhasil mengajukan barang!'
      end
    end
  end

  def history
    @history = History.all.where(masyarakat_id: current_user_m.id).order(created_at: :desc).where(nil)
    @history = History.all.where(masyarakat_id: current_user_m.id).order(created_at: :desc).where('created_at BETWEEN ? AND ?', params[:dari].to_date.beginning_of_day, params[:hingga].to_date.end_of_day) if params[:dari].present? && params[:hingga].present?
  end

  def profile
    @get_profile = Masyarakat.find(params[:id])
  end

  def update_profile
    @get_profile = Masyarakat.find(params[:id])
    if @get_profile.update(profile_m_params)
      redirect_to lelangind_profile_path, notice: 'Berhasil update profile'
    else
      render :profile
    end
  end

  private
  def profile_m_params
    params.require(:masyarakat).permit(:nama_lengkap, :username, :telp)
  end
end

app/helpers/lelangind_helper.rb
module LelangindHelper
end

app/views/lelangind/history.html.erb
<h2 class="uk-heading-divider">History Lelang</h2>

<div uk-grid>
    <div class="uk-width-1-3@m">
        <div class="uk-card uk-card-small uk-card-default uk-card-body">
            <h4>Cari History</h4>
            <%= form_tag lelangind_history_path, method: :get do %>
                <div class="uk-margin">
                    <label>Dari tanggal</label>
                    <%= date_field_tag :dari, params[:dari], max: DateTime.current.to_date, class: 'uk-input' %>
                </div>
                <div class="uk-margin">
                    <label>Hingga tanggal</label>
                    <%= date_field_tag :hingga, params[:hingga], max: DateTime.current.to_date, class: 'uk-input' %>
                </div>
                <div class="uk-margin">
                    <%= submit_tag 'Cari', class: 'uk-button uk-button-secondary uk-width-1-1', style: 'background-color: #3b3b3b;' %>
                </div>
            <% end %>
        </div>
    </div>
    <div class="uk-width-expand@m">
        <% if @history.blank? %>
            <div class="uk-text-center">
                <br>
                <br>
                <img src="/Asset/img/accs/empty.svg" width="300" alt="">
                <h3>Tidak ada history.</h3>
            </div>
        <% else %>
            <% @history.each do |h| %>
                <div class="uk-card uk-card-small uk-border-rounded uk-card-hover uk-card-default uk-card-body uk-margin">
                    <p class="uk-text-meta uk-text-small uk-margin-remove-top uk-margin-remove-bottom">tanggal : <%= h.created_at.strftime('%d-%m-%Y') %></p>
                    <h3 class="uk-text-capitalize uk-margin-remove-bottom uk-margin-remove-top"><%= link_to h.barang.nama_barang, lelangind_ikut_lelang_path(h.lelang.id), class: 'uk-text-bolder', style: 'text-decoration: none; color: #3b3b3b;' %></h3>
                    <table>
                        <tr>
                            <td>Penawaran</td>
                            <td>:</td>
                            <td class="uk-text-primary">Rp. <%= number_with_delimiter(h.penawaran_harga) %></td>
                        </tr>
                        <tr>
                            <td>Status</td>
                            <td>:</td>
                            <% if h.lelang.status == 'dibuka' %>
                                <td class="uk-text-success">Lelang sedang berlangsung</td>
                            <% elsif h.lelang.status == 'ditutup' %>
                                <td class="uk-text-danger">Lelang sudah selesai</td>
                            <% else %>

                            <% end %>
                        </tr>
                    </table>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/lelangind/ikut_lelang.html.erb
<% if notice %>
    <div class="uk-alert-success" uk-alert>
        <a class="uk-alert-close" uk-close></a>
        <p><%= notice %></p>
    </div>
<% end %>
<% if alert %>
    <div class="uk-alert-danger" uk-alert>
        <a class="uk-alert-close" uk-close></a>
        <p><%= alert %></p>
    </div>
<% end %>
<% lelang = Lelang.find(@item.id) %>
<div>
    <ul class="uk-breadcrumb">
        <li><%= link_to 'home', lelangind_index_path %></li>
        <li><%= link_to 'lelang', lelangind_lelang_barang_path %></li>
        <li><span><%= lelang.barang.nama_barang %></span></li>
    </ul>
</div>
<div uk-grid>
    <div class="uk-width-2-5@m">
        <div class="uk-card uk-card-small uk-card-default">
            <div class="uk-card-body">
                <img src="<%= lelang.barang.img_barang %>" alt="<%= lelang.barang.nama_barang %>">
            </div>
        </div>
    </div>
    <div class="uk-width-expand@m">
        <div class="uk-card uk-card-small uk-card-default uk-margin">
            <div class="uk-card-header">
                <h4 class="uk-card-title uk-text-capitalize uk-text-bolder uk-margin-remove-bottom"><%= lelang.barang.nama_barang %></h4>
            </div>
            <div class="uk-card-body">
                <div class="uk-margin uk-margin-remove-bottom">
                    <label class="uk-text-meta uk-margin-remove-bottom">Tanggal dibuat</label>
                    <p class="uk-margin-remove-top uk-margin-remove-bottom"><%= lelang.tgl_lelang.strftime("%d-%m-%Y") %></p>
                </div>
                <hr class="uk-margin-remove-top uk-margin-remove-bottom">
                <div class="uk-margin uk-margin-remove-top uk-margin-remove-bottom">
                    <label class="uk-text-meta uk-margin-remove-bottom">Harga awal</label>
                    <p class="uk-margin-remove-top uk-text-primary uk-margin-remove-bottom">Rp. <%= number_with_delimiter(lelang.barang.harga_awal) %></p>
                </div>
                <hr class="uk-margin-remove-top uk-margin-remove-bottom">
                <div class="uk-margin uk-margin-remove-top uk-margin-remove-bottom">
                    <label class="uk-text-meta uk-margin-remove-bottom">Status</label>
                    <p class="uk-margin-remove-top uk-text-capitalize uk-text-success uk-margin-remove-bottom"><%= @item.status %></p>
                </div>
                <hr class="uk-margin-remove-top uk-margin-remove-bottom">
                <div class="uk-margin uk-margin-remove-top">
                    <label class="uk-text-meta uk-margin-remove-bottom">Deskrpisi</label>
                    <p class="uk-margin-remove-top uk-text-capitalize uk-margin-remove-bottom"><%= lelang.barang.deskripsi_barang %></p>
                </div>
            </div>
        </div>
        <div class="uk-card uk-card-small uk-card-default">
            <div class="uk-card-header">
                <h4 class="uk-card-title uk-text-capitalize uk-margin-remove-bottom uk-text-normal">Daftar penawaran <span class="uk-text-bolder" style="color: #3b3b3b;"><%= lelang.barang.nama_barang %></span></h4>
            </div>
            <div class="uk-card-body">
                <% if @item.status == 'ditutup' %>
                    <% n = Masyarakat.find(@item.masyarakat_id) %>
                    <h5 class="uk-margin-remove-bottom">Pemenang Lelang : <span class="uk-text-capitalize uk-text-primary"><%= n.nama_lengkap %></span></h5>
                    <% if lelang.histories.blank? %>
                    
                    <% else %>
                        <table class="uk-table uk-margin uk-table-small uk-table-divider uk-table-striped">
                            <caption></caption>
                            <thead>
                                <tr>
                                    <th class="uk-table-shrink">No</th>
                                    <th>Nama</th>
                                    <th>Penawaran</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% penawaran = lelang.histories.order(penawaran_harga: :desc) %>
                                <% penawaran.each.with_index do |h, index| %>
                                    <tr>
                                        <td><%= index+1 %></td>
                                        <td class="uk-text-capitalize"><%= h.masyarakat.nama_lengkap %></td>
                                        <td class="uk-text-danger">Rp. <%= number_with_delimiter(h.penawaran_harga) %></td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    <% end %>
                <% else %>
                    <% if lelang.histories.blank? %>
                        <div class="uk-text-center">
                            <h4>Ajukan penawaranmu sekarang!</h4>
                            <% if current_user_m %>
                                <button href="#modal-penawaran" class="uk-button uk-button-secondary uk-button-small uk-border-rounded uk-box-shadowm-medium" style="background-color: #3b3b3b;" uk-toggle>Ikut Lelang</button>
                            <% else %>
                                <h4 class="uk-text-meta">Ingin ikut lelang? silahkan <%= link_to 'Login', auth_new_path, class: 'uk-button uk-button-text' %></h4>
                            <% end %>
                        </div>
                    <% else %>
                        <% if current_user_m %>
                            <% find_user_histories = lelang.histories.find_by(masyarakat_id: current_user_m.id) %>
                            <% if find_user_histories.nil? %>
                                <%= form_tag controller: :lelangind, action: :penawaran do %>
                                    <p class="uk-margin-remove-bottom uk-margin-remove-top">Penawaran harus lebih tinggi dari <span class="uk-text-primary">Rp. <%= number_with_delimiter(lelang.histories.max.penawaran_harga) %></span></p>
                                    <div class="uk-grid-small uk-margin-remove-top" uk-grid>
                                        <div class="uk-width-1-2@s">
                                            <%= number_field_tag :penawaran_harga, '', class: 'uk-input', placeholder: 'Ajukan penawaran' %>
                                        </div>
                                        <div class="uk-width-1-4@s">
                                            <%= submit_tag 'Ajukan', class: 'uk-button uk-button-secondary', style: 'background-color: #3b3b3b;' %>
                                        </div>
                                    </div>
                                <% end %>
                            <% else %>
                                <p class="uk-margin-remove-bottom uk-margin-remove-top">Anda telah melakukan lelang pada produk ini.</p>
                            <% end %>
                        <% else %>
                            <h4 class="uk-text-meta">Ingin ikut lelang? silahkan <%= link_to 'Login', auth_new_path, class: 'uk-button uk-button-text' %></h4>
                        <% end %>

                        <table class="uk-table uk-table-small uk-table-divider uk-table-striped">
                            <caption></caption>
                            <thead>
                                <tr>
                                    <th class="uk-table-shrink">No</th>
                                    <th>Nama</th>
                                    <th>Penawaran</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% penawaran = lelang.histories.order(penawaran_harga: :desc) %>
                                <% penawaran.each.with_index do |h, index| %>
                                    <tr>
                                        <td><%= index+1 %></td>
                                        <td class="uk-text-capitalize"><%= h.masyarakat.nama_lengkap %></td>
                                        <td class="uk-text-danger">Rp. <%= number_with_delimiter(h.penawaran_harga) %></td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

<div id="modal-penawaran" uk-modal>
    <div class="uk-modal-dialog">
        <button class="uk-modal-close-default" type="button" uk-close></button>
        <div class="uk-modal-header">
            <h2 class="uk-modal-title">Ajukan Penawaran</h2>
        </div>
        <%= form_tag controller: :lelangind, action: :penawaran do %>
            <% if penawaran.blank? %>
                <div class="uk-modal-body">
                    <p>Penawaran pertama harus lebih dari <span class="uk-text-primary">Rp. <%= number_with_delimiter(lelang.barang.harga_awal) %></span></p>
                    <div class="uk-margin">
                        <label>Penawaran</label>
                        <%= number_field_tag :penawaran_harga, '', class: 'uk-input' %>
                    </div>
                </div>
                <div class="uk-modal-footer uk-text-right">
                    <button class="uk-button uk-button-default uk-modal-close" type="button">Cancel</button>
                    <%= submit_tag 'Ajukan', class: 'uk-button uk-button-secondary', style: 'background-color: #3b3b3b;' %>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/lelangind/index.html.erb
<% if notice %>
    <div class="uk-alert-success" uk-alert>
        <a class="uk-alert-close" uk-close></a>
        <p><%= notice %></p>
    </div>
<% end %>
<% if alert %>
    <div class="uk-alert-danger" uk-alert>
        <a class="uk-alert-close" uk-close></a>
        <p><%= alert %></p>
    </div>
<% end %>
<div class="uk-text-center">
    <br>
    <img src="/Asset/img/accs/take_lelang.svg" width="300" alt=""  uk-scrollspy="cls: uk-animation-slide-left; repeat: true; delay: 600">
    <div uk-scrollspy="cls: uk-animation-slide-right; repeat: true; delay: 1200">
        <h1 class="uk-text-bolder uk-text-uppercase uk-heading-medium" style="color: #3b3b3b;">Lelangind lelang online</h1>
        <h4 class="uk-text-light uk-margin-remove-top" style="color: #686c7b;">Cari dan temukan barang berkualitas untuk anda miliki! ayo ikut lelang sekarang!</h4>
    </div>
    <div uk-scrollspy="cls: uk-animation-slide-bottom; repeat: true; delay: 1800">
        <p uk-margin>
            <a class="uk-button uk-button-default" href="#kelebihan" uk-scroll>lebih lanjut</a>
            <%= link_to 'Lihat Lelang', lelangind_lelang_barang_path, class: 'uk-button uk-button-secondary', style: 'background-color: #3b3b3b;' %>
        </p>
    </div>
</div><br><br><br><br><br><hr><br><br>
<div class="uk-text-center" id="kelebihan" uk-scrollspy="cls: uk-animation-fade; target: #k; delay: 500; repeat: true">
    <h2 class="uk-text-normal" style="color: #3b3b3b;">Kenapa harus di <span class="uk-text-uppercase uk-text-bolder">Lelangind</span>?</h2>
    <h5 class="uk-text-light uk-margin-remove-top" style="color: #686c7b;">Kelebihan pada LELANGIND yang tidak ada pada aplikasi lain ada dibawah ini</h5>
    <br><br>
    <div class="uk-grid-column-small uk-grid-row-large uk-child-width-1-3@s uk-text-center" uk-grid>
        <div>
            <div id="k">
                <i class="fas fa-eye fa-5x"></i>
                <h2 class="uk-margin-medium-top uk-text-light">Pantau</h2>
                <p>Lelang barang selalu dipantau selama 24 jam, jangan khawatir lelang diabaikan.</p>
            </div>
        </div>
        <div>
            <div id="k">
                <i class="fas fa-phone-volume fa-5x"></i>
                <h2 class="uk-margin-medium-top uk-text-light">Dihubungi Langsung</h2>
                <p>Setelah lelang ditutup, pemenang akan dihubungi langsung oleh petugas.</p>
            </div>
        </div>
        <div>
            <div id="k">
                <i class="fas fa-shipping-fast fa-5x"></i>
                <h2 class="uk-margin-medium-top uk-text-light">Gratis Pengiriman</h2>
                <p>Pemanang lelang akan mendapat gratis biaya pengiriman barang.</p>
            </div>
        </div>
    </div>
</div>
<br><br>
<hr>
<br><br>
<div class="uk-text-center" uk-scrollspy="cls: uk-animation-fade; target: #l; delay: 500; repeat: true">
    <h2 id="l" class="uk-text-normal" style="color: #3b3b3b;">Tunggu apalagi <span class="uk-text-bolder uk-text-capitalize">daftarkan</span> dirimu sekarang juga!</h2>
    <h5 id="l" class="uk-text-light uk-margin-remove-top" style="color: #686c7b;">Gunakan kesempatan ini untuk menemukan barang barang menarik dengan harga yang menarik juga</h5>
    <p id="l" uk-margin>
        <% if current_user_m %>
            <%= link_to 'Lihat Lelang', lelangind_lelang_barang_path, class: 'uk-button uk-button-secondary', style: 'background-color: #3b3b3b;' %>
        <% else %>
            <%= link_to 'Daftar', auth_new_path, class: 'uk-button uk-button-secondary', style: 'background-color: #3b3b3b;' %>
        <% end %>
    </p>
</div>

app/views/lelangind/lelang.html.erb
<% if notice %>
    <div class="uk-alert-success" uk-alert>
        <a class="uk-alert-close" uk-close></a>
        <p><%= notice %></p>
    </div>
<% end %>
<div uk-grid>
    <div class="uk-width-1-3@m">
        <div class="uk-card uk-card-small uk-card-body uk-card-default">
            <div class="uk-margin">
                <span class="uk-label uk-background-secondary" style="background-color: #3b3b3b;">Info</span>
            </div>
            <div uk-slideshow="animation: push; autoplay: true; autoplay-interval: 3000; finite: true;">

                <div class="uk-position-relative uk-visible-toggle uk-light" tabindex="-1">
            
                    <ul class="uk-slideshow-items">
                        <li>
                            <img src="/Asset/img/slider/l1.jpg" alt="" uk-cover>
                        </li>
                        <li>
                            <img src="/Asset/img/slider/l2.jpg" alt="" uk-cover>
                        </li>
                        <li>
                            <img src="/Asset/img/slider/l3.jpg" alt="" uk-cover>
                        </li>
                    </ul>
            
                    <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#" uk-slidenav-previous uk-slideshow-item="previous"></a>
                    <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#" uk-slidenav-next uk-slideshow-item="next"></a>
            
                </div>
            
                <ul class="uk-slideshow-nav uk-dotnav uk-flex-center uk-margin"></ul>
            
            </div>
        </div>
    </div>
    <div class="uk-width-expand@m">
        <h2 class="uk-heading-divider">Barang Lelang</h2>
        <% if @lelang.blank? %>
            <div class="uk-text-center">
                <br>
                <br>
                <img src="/Asset/img/accs/empty.svg" width="300" alt="">
                <h3>Belum ada barang.</h3>
            </div>
        <% else %>
        <div class="uk-child-width-1-2@m uk-grid-small uk-grid-match" uk-grid>
            <% @lelang.each do |lelang| %>
                <div>
                    <div class="uk-card uk-card-default uk-card-small uk-card-hover">
                        <div class="uk-card-header">
                            <% find = Lelang.find(lelang.id) %>
                            <h4 class="uk-card-title uk-text-capitalize uk-margin-remove-bottom"><%= find.barang.nama_barang %></h4>
                            <p class="uk-text-meta uk-margin-remove-top">Dibuat: <%= lelang.tgl_lelang.strftime("%d-%m-%Y") %></p>
                        </div>
                        <div class="uk-card-body">
                            <%= image_tag("#{find.barang.img_barang}", { style: 'width:100%;height:250px;object-fit: cover;' }) %>
                            <div class="uk-margin">
                                <p class="uk-text-meta uk-margin-remove-bottom">Harga Awal</p>
                                <h4 class="uk-text-primary uk-margin-remove-top">Rp <%= number_with_delimiter(find.barang.harga_awal) %></h4>
                            </div>
                            <div class="uk-margin">
                                <p class="uk-text-meta uk-margin-remove-bottom">Penawaran Tertinggi</p>
                                <% penawaran_barang = Lelang.find(lelang.id) %>
                                <% harga_max = penawaran_barang.histories.max %>
                                <% if harga_max.nil? %>
                                    <h4 class="uk-text-primary uk-margin-remove-top uk-margin-remove-bottom">Rp. 0</h4>
                                <% else %>
                                    <h4 class="uk-text-danger uk-margin-remove-top uk-margin-remove-bottom">Rp <%= number_with_delimiter(harga_max.penawaran_harga) %></h4>
                                <% end %>
                            </div>
                        </div>
                        <div class="uk-card-footer">
                            <%= link_to 'Ikut Lelang', lelangind_ikut_lelang_path(lelang), class: 'uk-button uk-button-secondary uk-width-1-1', style: 'background-color: #3b3b3b;' %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
        <% end %>
    </div>
</div>

app/views/lelangind/profile.html.erb
<div uk-grid>
    <div class="uk-width-1-3@m">
        <div>
            <div class="uk-card uk-card-default uk-card-body">
                <h1 class="uk-heading-large uk-margin-remove-bottom uk-text-uppercase" style="color: #3b3b3b;"><%= @get_profile.nama_lengkap.first %></h1>
                <div class="uk-margin uk-margin-remove-top ">
                    <label class="uk-margin-remove-bottom uk-text-meta">Nama</label>
                    <h4 class="uk-text-capitalize uk-margin-remove-top "><%= @get_profile.nama_lengkap %></h4>
                </div>
                <div class="uk-margin uk-margin-remove-top ">
                    <label class="uk-margin-remove-bottom uk-text-meta">Username</label>
                    <h4 class="uk-margin-remove-top "><%= @get_profile.username %></h4>
                </div>
                <div class="uk-margin uk-margin-remove-top ">
                    <label class="uk-margin-remove-bottom uk-text-meta">Telp</label>
                    <h4 class="uk-text-capitalize uk-margin-remove-top "><%= @get_profile.telp %></h4>
                </div>
            </div>
        </div>
    </div>
    <div class="uk-width-expand@m">
        <div>
            <div class="uk-card uk-card-default">
                <div class="uk-card-header">
                    <h3>Edit Profile</h3>
                </div>
                <div class="uk-card-body">
                    <% if alert %>
                        <div class="uk-alert-danger" uk-alert>
                            <a class="uk-alert-close" uk-close></a>
                            <p><%= alert %></p>
                        </div>
                        <% end %>
                        <% if notice %>
                            <div class="uk-alert-success" uk-alert>
                                <a class="uk-alert-close" uk-close></a>
                                <p><%= notice %></p>
                            </div>
                        <% end %>
                        <% if @get_profile.errors.any? %>
                            <div class="uk-alert-danger" uk-alert>
                                <a class="uk-alert-close" uk-close></a>
                                <h5><%= pluralize(@get_profile.errors.count, "error") %> Upss!, tidak bisa update :</h5>
                                <hr>
                                <ul>
                                <% @get_profile.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                                <% end %>
                                </ul>
                            </div>
                    <% end %>
                    <%= form_with model: @get_profile, url: lelangind_update_profile_path, local: true do |f| %>
                        <div class="uk-margin uk-margin-remove-top">
                            <label class="uk-text-meta">Nama Lengkap</label>
                            <%= f.text_field :nama_lengkap, class: 'uk-input', autocomplete: 'off' %>
                        </div>
                        <div class="uk-margin">
                            <label class="uk-text-meta">Username</label>
                            <%= f.text_field :username, class: 'uk-input', autocomplete: 'off' %>
                        </div>
                        <div class="uk-margin">
                            <label class="uk-text-meta">Telp</label>
                            <%= f.number_field :telp, class: 'uk-input', autocomplete: 'off' %>
                        </div><br>
                        <div class="uk-margin uk-text-center">
                            <%= f.submit 'Update Profile', class: 'uk-button uk-button-secondary', style: 'background-color: #3b3b3b;' %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>