config/routes.rb
Rails.application.routes.draw do
  # lelangind
  root 'lelangind#index', as: 'lelangind_index'
  get 'lelang', to: 'lelangind#lelang', as: 'lelangind_lelang_barang'
  get 'lelang/:id/', to: 'lelangind#ikut_lelang', as: 'lelangind_ikut_lelang'
  post 'lelang/:id/', to: 'lelangind#penawaran', as: 'lelangind_ajukan_penawaran'
  get '/history/', to: 'lelangind#history', as: 'lelangind_history'
  get '/:id/profile', to: 'lelangind#profile', as: 'lelangind_profile'
  patch '/:id/profile/', to: 'lelangind#update_profile', as: 'lelangind_update_profile'

  # auth
  get '/auth/', to: 'auth#new',  as: 'auth_new'
  post '/create_m_auth', to: 'auth#create_m_auth', as: 'create_m_auth'
  post '/auth/', to: 'auth#create_m_user', as: 'create_m_user'
  get '/petugas/auth/', to: 'auth#new_p', as: 'auth_p_new'
  post '/create_p_auth', to: 'auth#create_p_auth', as: 'create_p_auth'
  delete '/destroy_session_m/:id', to: 'auth#destroy_session_m', as: 'destroy_s_m'
  delete '/destroy_session_p/:id', to: 'auth#destroy_session_p', as: 'destroy_s_p'

  # petugas
  get '/petugas/profile/:id', to: 'petugas#profile_petugas', as: 'profile_p'
  patch '/petugas/profile/:id', to: 'petugas#update_profile_p', as: 'update_profile_p'

  get '/petugas/', to: 'petugas#index', as: 'petugas_index'

  get '/petugas/pendataan-barang', to: 'petugas#pendataan_barang', as: 'data_barang_p'
  post '/petugas/pendataan-barang', to: 'petugas#create_new_barang', as: 'create_new_barang'
  get '/petugas/pendataan-barang/:id',to: 'petugas#detail_barang_item', as: 'detail_barang_item'
  get '/petugas/pendataan-barang/:id/edit', to: 'petugas#edit_barang', as: 'edit_barang'
  patch '/petugas/pendataan-barang/:id/edit', to: 'petugas#update_barang', as: 'update_barang'
  delete '/petugas/pendataan-barang/:id/delete', to: 'petugas#destroy_barang', as: 'destroy_barang' 

  get '/petugas/lelang/', to: 'petugas#barang_lelang', as: 'barang_lelang_p'
  get '/petugas/lelang/:id', to: 'petugas#barang_lelang_detail', as: 'barang_lelang_detail'
  post '/petugas/lelang/:id/buka-lelang', to: 'petugas#buka_lelang', as: 'buka_lelang'
  post '/petugas/lelang/:id/tutup-lelang', to: 'petugas#tutup_lelang', as: 'tutup_lelang'

  get '/petugas/daftar-petugas/', to: 'petugas#manage_petugas', as: 'manage_petugas'
  post '/petugas/daftar-petugas/', to: 'petugas#create_new_petugas', as: 'create_new_petugas'
  
  get '/petugas/laporan/', to: 'petugas#generate_laporan', as: 'laporan'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lelangind</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/lelangind.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lelangind - Home</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body uk-height-viewport>
    <nav class="uk-background uk-box-shadow-small" uk-navbar>
      <div class="uk-navbar-left">
  
          <ul class="uk-navbar-nav">
              <li class="<%= current_class_f?(lelangind_index_path) %>"><%= link_to 'Lelangind', lelangind_index_path %></li>
              <li class="<%= current_class_f?(lelangind_lelang_barang_path) %>"><%= link_to 'lelang', lelangind_lelang_barang_path %></li>
          </ul>
  
      </div>
      <div class="uk-navbar-right">
  
          <ul class="uk-navbar-nav">
              <% if current_user_m %>
                <li><%= link_to current_user_m.nama_lengkap, lelangind_profile_path(current_user_m) %></li>
                <li class="<%= current_class_f?(lelangind_history_path) %>"><%= link_to 'History', lelangind_history_path %></li>
                <li><%= link_to 'Logout', destroy_s_m_path(current_user_m), method: :delete %></li>
              <% else %>
                <li><%= link_to 'Masuk / daftar', auth_new_path %></li>
              <% end %>
          </ul>
      </div>
    </nav>
    <div class="uk-container uk-padding">
        <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/petugas.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lelangind - Petugas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <link rel="apple-touch-icon" sizes="76x76" href="/admin/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="/admin/assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'admin', 'data-turbolinks-track': 'reload' %>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <!-- CSS Files -->
    <link href="/admin/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/admin/assets/css/paper-dashboard.css?v=2.0.1" rel="stylesheet" />
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="/admin/assets/demo/demo.css" rel="stylesheet" />
  </head>

  <body>
    <div class="wrapper ">
      <div class="sidebar" data-color="white" data-active-color="danger">
        <div class="logo">
          <a href="https://www.creative-tim.com" class="simple-text logo-mini">
            <!-- <div class="logo-image-small">
              <img src="./assets/img/logo-small.png">
            </div> -->
            <!-- <p>CT</p> -->
          </a>
          <%= link_to 'Lelangind', lelangind_index_path, class: 'simple-text logo-normal' %>
        </div>
        <div class="sidebar-wrapper">
          <ul class="nav">
            <li class="<%= current_class?(petugas_index_path) %>">
              <%= link_to petugas_index_path do %>
                <i class="nc-icon nc-chart-pie-36"></i>
                <p>Dashboard</p>
              <% end %>
            </li>
            <li class="<%= current_class?(data_barang_p_path) %>">
              <%= link_to data_barang_p_path do %>
                <i class="nc-icon nc-app"></i>
                <p>Pendataan Barang</p>
              <% end %>
            </li>
            <% if current_user_p.level_id == 1 %>
              <li class="<%= current_class?(manage_petugas_path) %>">
                <%= link_to manage_petugas_path do %>
                  <i class="nc-icon nc-single-02"></i>
                  <p>Petugas</p>
                <% end %>
              </li>
              <li class="<%= current_class?(barang_lelang_p_path) %>">
                <%= link_to barang_lelang_p_path do %>
                  <i class="nc-icon nc-bullet-list-67"></i>
                  <p>Lelang Barang</p>
                <% end %>
                </li>
            <% elsif current_user_p.level_id == 2 %>
              <li class="<%= current_class?(barang_lelang_p_path) %>">
              <%= link_to barang_lelang_p_path do %>
                <i class="nc-icon nc-bullet-list-67"></i>
                <p>Lelang Barang</p>
              <% end %>
              </li>
            <% else %>

            <% end %>
            <li class="<%= current_class?(laporan_path) %>">
              <%= link_to laporan_path do %>
                <i class="nc-icon nc-single-copy-04"></i>
                <p>Laporan</p>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <div class="main-panel" style="height: 100vh;">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
          <div class="container-fluid">
            <div class="navbar-wrapper">
              <div class="navbar-toggle">
                <button type="button" class="navbar-toggler">
                  <span class="navbar-toggler-bar bar1"></span>
                  <span class="navbar-toggler-bar bar2"></span>
                  <span class="navbar-toggler-bar bar3"></span>
                </button>
              </div>
              <%= link_to 'Lelangind', '#', class: 'navbar-brand' %>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-bar navbar-kebab"></span>
              <span class="navbar-toggler-bar navbar-kebab"></span>
              <span class="navbar-toggler-bar navbar-kebab"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navigation">
              <ul class="navbar-nav navbar-right">
                <li class="nav-item <%= current_class?(profile_p_path(current_user_p)) %>">
                  <%= link_to 'Profile', profile_p_path(current_user_p), class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Logout', destroy_s_p_path(current_user_p), class: 'nav-link', method: :delete %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
        <div class="content">
          <div class="row">
            <div class="col-md-12">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--   Core JS Files   -->
    <script src="/admin/assets/js/core/jquery.min.js"></script>
    <script src="/admin/assets/js/core/popper.min.js"></script>
    <script src="/admin/assets/js/core/bootstrap.min.js"></script>
    <script src="/admin/assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
    <!-- Chart JS -->
    <script src="/admin/assets/js/plugins/chartjs.min.js"></script>
    <!--  Notifications Plugin    -->
    <script src="/admin/assets/js/plugins/bootstrap-notify.js"></script>
    <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="/admin/assets/js/paper-dashboard.min.js?v=2.0.1" type="text/javascript"></script>
  </body>
</html>